### ISSUE TITLE
Validate check return true on empty string

### ISSUE THREAD

**Issue by marijnschilling** [3lvis/FormTextField#21]

**Comment by 3lvis** [comment]
Could you provide some steps to reproduce with current and expected results?

**Comment by marijnschilling** [comment]
When I select the empty textField I see the checkMark

**Comment by marijnschilling** [comment]
Also found other issue with setting the value for the accessory view too late.

**Comment by 3lvis** [comment]
Seems like this is no longer an issue. Closing.
