### ISSUE TITLE
unable to build with xcode 8.3.2

### ISSUE THREAD

**Issue by wajahatch888** [3lvis/FormTextField#32]
I am using latest version of FormTextField and i am getting following error

![screen shot 2017-05-23 at 3 40 01 pm](https://cloud.githubusercontent.com/assets/5916442/26350815/271a8754-3fce-11e7-807a-7d0936c087ad.png)

**Comment by 3lvis** [comment]
@wajahatch888 Could try deleting your pods and install again? Can you share your Podfile.lock with me?

**Comment by 3lvis** [comment]
Should be working fine, could you try again?

https://github.com/3lvis/FormTextField/releases
