### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ir-fuel** [3lvis/FormTextField#46]
The link to the formatters documentation gives a 404

**Comment by 3lvis** [comment]
Hi @ir-fuel 

It pointed out to the old repo, anything I can clarify? :)

https://github.com/Foreverland/Formatter/tree/master/Archived

**Comment by ir-fuel** [comment]
Not really. I decided not to use the package, but I just wanted to point out the dead link since there is basically no info whatsoever about the formatters :)

**Comment by 3lvis** [comment]
OK! Thanks for the feedback either way. I'll fix it.
